baseURL = 'https://www.cantara.app'
title = 'Cantara Song'
theme = 'hugo-theme-learn'
canonifyurls = true

defaultContentLanguage = "en"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[Languages]
    [Languages.en]
    title = 'Cantara Song'
    weight = 1
    languageName = 'English'
    [Languages.de]
    title = 'Cantara Liedpräsentation'
    weight = 2
    languageName = 'Deutsch'



[[menu.shortcuts]]
disableShortcutsTitle=true
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/reckel-jm/cantara"
weight = 10
